/* DADASHMODE v3 · domain data: segment types, games, emotions, themes, default episode */
'use strict';
const TYPES={title:'افتتاحیه',intro:'معرفی بازی (تمام‌صفحه)',rules:'قوانین (انیمیشنی)',countdown:'شمارش معکوس',play:'بازی زنده',bank:'وضعیت بانک زمان',dialogue:'دیالوگ',winner:'اعلام برنده',card:'کارت متنی'};
const TYPE_ALIAS={'افتتاحیه':'title','شروع':'title','معرفی':'intro','قوانین':'rules','قانون':'rules','شمارش':'countdown','بازی':'play','بانک':'bank','امتیاز':'bank','دیالوگ':'dialogue','گفتگو':'dialogue','برنده':'winner','کارت':'card','متن':'card'};
const GAMES={generic:'عمومی',cup:'برج لیوان',distance:'فاصله را خودت انتخاب کن',sandwich:'دوئل ساندویچ',glue:'دستکش، پازل و چسب',shop:'فروشگاه کارت',risk:'شوت ریسک',vault:'فینال · گاوصندوق',case:'کیف طلایی سه‌لایه'};
const GAME_ALIAS={'لیوان':'cup','برج':'cup','فاصله':'distance','پرتاب':'distance','ساندویچ':'sandwich','دوئل':'sandwich','چسب':'glue','پازل':'glue','دستکش':'glue','فروشگاه':'shop','کارت':'shop','بانک باز شد':'shop','ریسک':'risk','شوت':'risk','گاوصندوق':'vault','فینال':'vault','رمز':'vault','کیف':'case','تاج':'case','مجازات':'case'};
const EMO={
  excited:{fa:'هیجان‌زده',ins:'Energetic and thrilled, like a top TV game-show host hyping a live studio crowd. Big smile in the voice, bright and punchy.',rate:1.08,pitch:1.15},
  warm:{fa:'گرم و صمیمی',ins:'Warm, friendly and inviting, like talking to close friends. Smiling, relaxed pace.',rate:1,pitch:1.05},
  suspense:{fa:'تعلیق',ins:'Suspenseful and mysterious. Lower, slower, with dramatic pauses, building tension right before a reveal.',rate:.88,pitch:.95},
  whisper:{fa:'نجوا و رازآلود',ins:'Close, breathy half-whisper, secretive and intimate, as if sharing a secret with the camera.',rate:.9,pitch:1},
  serious:{fa:'جدی و قاطع',ins:'Firm, clear and authoritative, stating an important rule. Confident, crisp articulation.',rate:.95,pitch:1},
  referee:{fa:'داور سخت‌گیر',ins:'A sharp, strict referee making an instant call. Short, decisive, loud and clear, zero hesitation.',rate:1.05,pitch:1.05},
  playful:{fa:'شوخ و بامزه',ins:'Playful and teasing, a light laugh in the voice, cheeky comic timing.',rate:1.05,pitch:1.15},
  taunt:{fa:'کُری‌خوانی',ins:'Cheeky trash-talk between friends, confident smirk in the voice, provocative but fun.',rate:1.03,pitch:1.1},
  calm:{fa:'آرام و توضیحی',ins:'Calm, clear explainer tone, like a friendly teacher explaining game rules step by step. Every word easy to understand.',rate:.97,pitch:1.03},
  epic:{fa:'حماسی',ins:'Epic, grand and powerful like a movie-trailer announcer, heavy emphasis, slow build.',rate:.9,pitch:.95},
  celebrate:{fa:'جشن و پیروزی',ins:'Ecstatic celebration, cheering a winner, overflowing joy and energy, almost shouting with happiness.',rate:1.1,pitch:1.2},
  shock:{fa:'شوکه',ins:'Genuinely shocked and amazed, gasping, as if something unbelievable just happened on stage.',rate:1.05,pitch:1.15}};
const GEMINI_VOICES=[['Aoede','نسیمی و روان'],['Leda','جوان و شاداب'],['Zephyr','روشن و پرانرژی'],['Kore','محکم و مطمئن'],['Laomedeia','سرحال و پرانرژی'],['Autonoe','روشن'],['Callirrhoe','راحت و خودمانی'],['Despina','نرم و صاف'],['Erinome','شفاف'],['Achernar','لطیف'],['Sulafat','گرم'],['Vindemiatrix','ملایم'],['Pulcherrima','رو به جلو'],['Gacrux','پخته'],['Puck','شاد (مردانه)'],['Charon','اطلاع‌رسان (مردانه)'],['Fenrir','هیجانی (مردانه)'],['Orus','محکم (مردانه)']];
const OPENAI_VOICES=['coral','nova','shimmer','sage','ballad','marin','alloy','verse','ash','echo','fable','onyx','cedar'];
const THEMES=[
  {name:'استودیو قرمز',bg1:'#12060a',bg2:'#4f0d1c',accent:'#ff3b3b',accent2:'#ffd23f',ink:'#fff7ec',shade:'#7a0f1f'},
  {name:'گرگ نئونی',bg1:'#040b16',bg2:'#0b3050',accent:'#00e5ff',accent2:'#ff2d6f',ink:'#f2fbff',shade:'#063a5c'},
  {name:'کیف طلایی',bg1:'#0d0a05',bg2:'#3a2a0a',accent:'#ffc53d',accent2:'#ff7a1a',ink:'#fffaf0',shade:'#8a5a00'},
  {name:'آب‌نبات',bg1:'#1b0b4a',bg2:'#5b21d6',accent:'#39ff88',accent2:'#ffe14d',ink:'#fffdf7',shade:'#2a0f7a'},
  {name:'آرنای سایبری',bg1:'#05060f',bg2:'#1c1446',accent:'#7cf7ff',accent2:'#ffe600',ink:'#f5f7ff',shade:'#2b1d73'},
  {name:'یخ و برق',bg1:'#06142e',bg2:'#1d4ed8',accent:'#7dd3fc',accent2:'#fef08a',ink:'#f8fbff',shade:'#0b2a6b'},
  {name:'جنگل',bg1:'#04140a',bg2:'#0f5132',accent:'#a3e635',accent2:'#fb923c',ink:'#f7fff0',shade:'#14532d'},
  {name:'غروب داغ',bg1:'#1a0505',bg2:'#8a1c0a',accent:'#ff8a00',accent2:'#fff06a',ink:'#fff8ee',shade:'#6b1204'}];
const COLOR_KEYS={bg1:'پس‌زمینه تیره',bg2:'پس‌زمینه روشن',accent:'رنگ اصلی',accent2:'رنگ دوم',ink:'متن',shade:'سایه عمق'};
const FONTS={'Lalezar':'لاله‌زار · سنگین و تلویزیونی','Marhey':'مرحی · فانتزی و بامزه','Estedad':'استعداد · مدرن و محکم','Vazirmatn':'وزیرمتن · تمیز','Noto Kufi Arabic':'کوفی · رسمی'};
/* V7 card shop (book §4.2) · used by the shop illustration */
const POWERS=[{id:'HINT',cat:'آبی',name:'ذره‌بین',cost:10,desc:'یک بار کمک در حافظه یا معما'},{id:'SHIELD',cat:'آبی',name:'سپر',cost:5,desc:'یک کارت قرمز را خنثی می‌کند'},{id:'GLOVES',cat:'قرمز',name:'دستکش بوکس',cost:15,desc:'حریف اتاق حافظه را با دستکش انجام می‌دهد'},{id:'SPICY',cat:'قرمز',name:'معمای تند',cost:10,desc:'معمای حریف سخت‌تر می‌شود (همان جواب)'},{id:'MIRROR',cat:'طلایی',name:'آینه',cost:20,desc:'کارت قرمز به خریدارش برمی‌گردد'}];
const DIST={green:{fa:'سبز · ۲ متر',sec:5,col:'#22c55e'},yellow:{fa:'زرد · ۳ متر',sec:10,col:'#facc15'},red:{fa:'قرمز · ۴ متر',sec:20,col:'#ef4444'}};

const L=(emotion,text,direction='')=>({id:uid(),speaker:'host',emotion,text,direction});
function mkSeg(o){return Object.assign({id:uid(),type:'card',game:'generic',title:'',subtitle:'',rules:[],duration:30,reward:10,notes:'',issue:'',status:'draft',winner:'',lines:[]},o)}

function defaultEpisode(){return {
  format:'dadashmode-episode/3',v7book:'7.1',name:'داداش‌مود · بانک زمان · قسمت ۱ (کتاب V7)',unit:'ثانیه',startBank:45,
  speakers:[{id:'host',name:'جمنای (داور · صدای پشتیبان اپ)',provider:'gemini',voice:'Leda'}],
  players:[{id:'elias',name:'اِلیاس',color:'#ff2738',symbol:'▲',key:'a'},{id:'emad',name:'عِماد',color:'#00c98d',symbol:'●',key:'l'}],
  theme:Object.assign({font:'Lalezar'},THEMES[0]),
  brief:{summary:'دوئل الیاس و عماد طبق کتاب کارگردانی V7: شروع ۴۵|۴۵ · برج لیوان · فاصله · دوئل ساندویچ · بانک باز شد · پازل چسبی و چالش چسب · رونمایی (سقف ۳۰) · فروشگاه ۵ کارت · شوت ریسک · گاوصندوق سه‌ایستگاهی · کیف سه‌لایه.',tone:'جمنای داور خشک، منصف و کم‌حرف؛ هیچ عددی جز آنچه کارگردان از اپ می‌خواند نمی‌گوید. حین دوئل ساندویچ سکوت کامل.',characters:['اِلیاس · قرمز · E · کلید A','عِماد · سبز · M · کلید L','جمنای · داور هوش مصنوعی (بنفش) · اپ = منبع حقیقت اعداد'],beats:['هوک و معرفی (۴۵|۴۵)','راند ۱ تا ۴ + پیچش «بانک باز شد»','رونمایی، فروشگاه کارت، شوت ریسک','فینال گاوصندوق و کیف سه‌لایه'],directorNotes:['اپ تنها منبع اعداد است؛ جمنای فقط تکرار می‌کند','ایمنی دوئل ساندویچ: ناظر هایملیچ، کلمهٔ توقف «قرمز»','رمز کیف قبل از REC در اپ مهر شود']},
  segments:[
    mkSeg({type:'title',title:'داداش‌مود',subtitle:'بانک زمان · هوک',v7:'READY',notes:'هوک ۰۰:۰۰–۰۰:۳۰ · تایمر نارنجی ۰۰:۰۸ تا صفر + تیک‌تاک · فلش‌فوروارد نقاشی کور و شوت ریسک (بدون لو دادن نتیجه) · ثانیهٔ ۱۳ الیاس: «هر بازی رو ببریم، برای آخر ویدیو زمان می‌گیریم.» · عماد: «و آخرش… این جعبه مال منه.»',status:'ok',lines:[L('suspense','سه… دو…'),L('serious','و من داورم. پس تقلب ممنوع.')]}),
    mkSeg({type:'bank',title:'بانک زمان',subtitle:'هر نفر ۴۵ ثانیه',v7:'READY',notes:'۳٫۲ معرفی و قانون · کارت قوانین اپ: سقف فاصله ۳۰ و کف ۲۰ دیده می‌شود ولی گفته نمی‌شود · الیاس: «قانون ساده‌ست: هر کدوم ۴۵ ثانیه داریم…»',status:'ok',lines:[L('warm','آماده‌ام. من فقط چیزی رو می‌گم که می‌بینم. و الیاس… دیدمت که داشتی می‌خندیدی.'),L('serious','من طرف هیچ‌کس نیستم. طرف قانونم.')]}),
    mkSeg({type:'intro',game:'cup',title:'برج لیوان با یک دست',subtitle:'راند یک',v7:'R1',status:'ok',lines:[L('serious','راند یک. ده لیوان، فقط با یک دست. برج باید دو ثانیه سالم بمونه.')]}),
    mkSeg({type:'rules',game:'cup',title:'قوانین برج لیوان',v7:'R1',rules:['۱۰ لیوان · برج ۱-۲-۳-۴','دست دیگر پشت کمر · دست دوم = خطا و از نو','سقف ۳۰ ثانیه · هم‌زمان · افتادن = از نو','برج باید ۲ ثانیه بعد از برداشتن دست سالم بماند','اولین برج معتبر ۱۰+ · هیچ‌کس: طبقهٔ بیشتر ۵+'],status:'ok',lines:[L('calm','ده لیوان، برج یک، دو، سه، چهار.'),L('serious','دست دوم پشت کمر. دست دوم بیاد، خطاست.'),L('calm','سی ثانیه، هم‌زمان. ریخت؟ از نو.'),L('suspense','برج باید دو ثانیه سالم بمونه.'),L('excited','اولین برج سالم، ده ثانیه.')]}),
    mkSeg({type:'countdown',title:'دست دوم پشت کمر · شروع!',v7:'R1',status:'ok'}),
    mkSeg({type:'play',game:'cup',title:'برج لیوان',subtitle:'راند یک',v7:'R1',notes:'دکمهٔ «معتبر؟» شمارش ۲ ثانیه را شروع می‌کند (نه جمنای) · کلید: ۲/۱ معتبر · ۳/۴ ریخت',duration:30,reward:10,status:'ok',lines:[L('referee','دست دوم!'),L('playful','برجت زلزله اومد یا خودت زلزله‌ای؟')]}),
    mkSeg({type:'intro',game:'distance',title:'فاصله را خودت انتخاب کن',subtitle:'راند دو',v7:'R2',status:'ok',lines:[L('serious','راند دو. خطت رو انتخاب کن. بعد از قفل، عوض نمی‌شه.')]}),
    mkSeg({type:'rules',game:'distance',title:'قوانین پرتاب',v7:'R2',rules:['خط ۲ متر ۵+ · ۳ متر ۱۰+ · ۴ متر ۲۰+','یک بار انتخاب و قفل در اپ','۳ پرتاب، نوبتی، نفر عقب اول','اولین گل ارزش خط را می‌گیرد؛ بقیه صفر','پا روی خط = پرتاب باطل (شمرده می‌شود)'],status:'ok',lines:[L('calm','سه خط: دو متر پنج، سه متر ده، چهار متر بیست ثانیه.'),L('serious','یک بار انتخاب می‌کنید و قفل می‌شه.'),L('calm','سه پرتاب، نوبتی. نفر عقب اول.'),L('excited','اولین گل، ارزش خط رو می‌گیره.'),L('referee','پا روی خط، پرتاب باطل.')]}),
    mkSeg({type:'play',game:'distance',title:'فاصله را خودت انتخاب کن',subtitle:'راند دو',v7:'R2',notes:'ری‌هوک ۰۳:۰۰ · AI-CAM ۴۵ درجه به سمت سطل',duration:60,reward:20,status:'ok',lines:[L('referee','انتخاب قفل شد.'),L('playful','من باد رو نمی‌بینم. پرتابت رو دیدم.')]}),
    mkSeg({type:'intro',game:'sandwich',title:'دوئل ساندویچ',subtitle:'راند سه',v7:'R3_SANDWICH',status:'ok',lines:[L('serious','راند سه. دوئل ساندویچ. اوّلی که قورت بده، وقت می‌بره.')]}),
    mkSeg({type:'rules',game:'sandwich',title:'قوانین دوئل ساندویچ',v7:'R3_SANDWICH',rules:['دو ساندویچ یکسان · دست‌ها پشت کمر تا بوق','سقف ۶۰ ثانیه · «دهان‌پر» = ساعت می‌ایستد (زرد، موقت)','۳۰ ثانیه برای قورت + دهان خالی ۲ ثانیه به تروث‌کم','برنده = اختلاف زمان (کف ۳+ · سقف ۲۰+) · زیر ۱ ثانیه: هر دو ۵+','برگشت غذا = رد · تکهٔ بیرون بشقاب یا شروع زودتر = ۳ ثانیه جریمه','کلمهٔ توقف «قرمز» · ایمنی بالاتر از برد'],status:'ok',lines:[L('calm','دو ساندویچ یکسان. دست‌ها پشت کمر تا بوق.'),L('serious','آخرین لقمه رفت تو دهن، دستا بالا.'),L('calm','بعد سی ثانیه وقت دارید قورت بدید و دهن خالی نشون بدید.'),L('excited','برنده، اختلاف زمان رو می‌گیره. حداقل سه، حداکثر بیست ثانیه.'),L('referee','برگشت غذا یعنی رد.'),L('serious','هر کس بگه «قرمز»، همه‌چی همون لحظه متوقف می‌شه.')]}),
    mkSeg({type:'countdown',title:'سه… دو… یک…',v7:'R3_SANDWICH',notes:'از بوق تا اولین «دهان خالی»: جمنای و کارگردان ساکت (قانون سکوت)',status:'ok'}),
    mkSeg({type:'play',game:'sandwich',title:'دوئل ساندویچ',subtitle:'راند سه',v7:'R3_SANDWICH',notes:'کلیدها: ۹/۷ دهان‌پر · ۳/۱ دهان خالی ✔ · ۶/۴ جریمهٔ ۳ ثانیه · Enter تأیید نتیجه · ناظر هایملیچ کنار تروث‌کم · اورژانس ۱۱۵',duration:60,reward:20,status:'ok',lines:[L('playful','خالیه. مثل یخچال خونه‌ی دانشجویی.'),L('referee','طبق قانون… رد. ساندویچ حقّ اعتراض نداره.'),L('serious','استپ! اول قورت، بعد خنده.')]}),
    mkSeg({type:'play',game:'shop',title:'بانک باز شد',subtitle:'BANK OPEN · آبی برای خودت · قرمز برای حریف · طلایی برای شجاع‌ها',v7:'TWIST_BANKOPEN',notes:'پیچش میانی ۰۵:۲۰ · گلیچ طلایی + صدای قفل · ۵ کارت قفل ۶ ثانیه · زوم روی دستکش · هیچ عددی عوض نمی‌شود',duration:30,reward:0,status:'ok',lines:[L('shock','نه. بانک باز شد.'),L('serious','از الان ثانیه‌ها پول هم هستن. بعد از راند چهار، فروشگاه کارت باز می‌شه.'),L('suspense','آبی برای خودت. قرمز برای حریف. طلایی… برای شجاع‌ها.'),L('taunt','می‌تونی. ولی هر چی بخری، از ساعت فینالت کم می‌شه.'),L('playful','تو راند بعد باهاش آشنا می‌شید.')]}),
    mkSeg({type:'intro',game:'glue',title:'دستکش، پازل و چسب',subtitle:'راند چهار',v7:'R4_GLUE',status:'ok',lines:[L('serious','راند چهار. دستکش‌ها رو بپوشید. پازل لوگو، شیش تیکه. چیدن با دستکش، چسب بی دستکش. اوّلی که دکمه‌ی تمام رو بزنه، پونزده ثانیه.')]}),
    mkSeg({type:'rules',game:'glue',title:'قوانین پازل چسبی',v7:'R4_GLUE',rules:['پازل ۶ تکهٔ لوگو (۳×۲) · چاپ سیاه‌وسفید','فاز ۱: چیدن با دستکش','فاز ۲: چسب بدون دستکش (وقتی هر ۶ تکه روی برگه است)','فاز ۳: دکمهٔ «تمام» · غلط = لغو + ۵ ثانیه قفل','سقف ۱۸۰ · اولین تمام معتبر ۱۵+ · هیچ‌کس: درست‌تر ۵+','چالش چسب (یک بار، نفر دوم): موفق ۱۰/۵ · ناموفق ۵−'],status:'ok',lines:[L('calm','پازل لوگو، شیش تیکه.'),L('playful','اول با دستکش می‌چینید.'),L('calm','دستکش فقط وقتی درمیاد که هر شیش تیکه روی برگه باشه. بعد چسب.'),L('referee','دکمه‌ی تمام. اگه غلط باشه، لغو و پنج ثانیه قفل.'),L('excited','اوّلین تمام درست، پونزده ثانیه.'),L('suspense','نفر دوم یک بار حق داره بگه: چالش!')]}),
    mkSeg({type:'play',game:'glue',title:'دستکش، پازل و چسب',subtitle:'راند چهار',v7:'R4_GLUE',notes:'کلیدها: ۲/۱ تمام · ۰ غلط · * چالش چسب',duration:180,reward:15,status:'ok',lines:[L('referee','سر گرگ برعکسه. ادامه بدید.'),L('referee','یه تیکه هنوز رو میزه. دستکش برمی‌گرده.')]}),
    mkSeg({type:'play',game:'glue',title:'چالش چسب',subtitle:'تست تکان ← قاب ← تمیزی',v7:'GLUE_CHALLENGE',notes:'۳ معیار ثابت: تست تکان (کارگردان + تروث‌کم) · قاب و تراز (جمنای) · تمیزی فقط اگر مساوی',duration:30,reward:10,status:'ok',lines:[L('serious','تست تکان.'),L('referee','تشخیص نمی‌دم.')]}),
    mkSeg({type:'play',game:'generic',title:'رونمایی بانک',subtitle:'سقف فاصله ۳۰',v7:'REVEAL',duration:20,reward:0,status:'ok',lines:[L('suspense','سی. دقیقاً روی مرز. قانون اعمال نمی‌شه.')]}),
    mkSeg({type:'rules',game:'shop',title:'فروشگاه کارت و دردسر',v7:'SHOP',rules:['🔍 ذره‌بین ۱۰ · آبی · یک بار کمک','🛡 سپر ۵ · آبی · قرمز را خنثی می‌کند','🥊 دستکش بوکس ۱۵ · قرمز · حافظه با دستکش','🌶 معمای تند ۱۰ · قرمز · معمای سخت‌تر','🪞 آینه ۲۰ · طلایی · قرمز برمی‌گردد','حداکثر ۲ کارت · فقط ۱ قرمز · مالیات ۵ نفر جلو · کف ۲۰'],status:'ok',lines:[L('calm','ذره‌بین، ده ثانیه. یک بار کمک.'),L('calm','سپر، پنج ثانیه. قرمز رو خنثی می‌کنه.'),L('taunt','دستکش بوکس، پونزده. حافظه با دستکش.'),L('taunt','معمای تند، ده. معمای سخت‌تر.'),L('suspense','آینه، بیست. قرمز برمی‌گرده.'),L('serious','حداکثر دو کارت. فقط یکی قرمز. مخفی.')]}),
    mkSeg({type:'play',game:'shop',title:'فروشگاه کارت',subtitle:'خرید مخفی · نفر عقب اول',v7:'SHOP',notes:'کلیدها: ۴ تا ۸ کارت برای نفری که نوبت اوست · Enter ثبت/رونمایی',duration:60,reward:0,status:'ok',lines:[L('serious','فروشگاه کارت باز شد. هر نفر حداکثر دو کارت. فقط یکی قرمز. مخفی.')]}),
    mkSeg({type:'play',game:'shop',title:'رونمایی کارت‌ها',subtitle:'آینه ← سپر ← اجرا',v7:'SHOP_REVEAL',duration:20,reward:0,status:'ok',lines:[L('shock','آینه! کارت برگشت به صاحبش.'),L('referee','کارت قرمز سوخت. سپر فعال شد.')]}),
    mkSeg({type:'rules',game:'risk',title:'شوت ریسک',v7:'RISK',rules:['شرط علنی: ۰ / ۱۰ / ۲۰','نفر عقب اول اعلام می‌کند','«همه‌چی ۳۰» فقط برای نفر ۱۵+ ثانیه عقب','خورد = + شرط · نخورد = − شرط','بانک هرگز زیر ۲۰ نمی‌رود'],status:'ok',lines:[L('calm','شرط علنی: صفر، ده یا بیست.'),L('serious','اول نفر عقب اعلام می‌کنه.'),L('suspense','همه‌چی سی، فقط برای کسی که پونزده ثانیه عقبه.'),L('excited','خورد، شرطت اضافه می‌شه. نخورد، کم می‌شه.'),L('referee','بانک هیچ‌وقت زیر بیست نمی‌ره.')]}),
    mkSeg({type:'play',game:'risk',title:'شوت ریسک',subtitle:'شرط علنی',v7:'RISK',notes:'کلیدها: ۹/۶ الیاس خورد/نخورد · ۷/۴ عماد خورد/نخورد',duration:60,reward:0,status:'ok',lines:[L('serious','شوت ریسک. اوّل نفر عقب اعلام می‌کنه.'),L('referee','نخورد. دو سانت. دو سانت دردناک.')]}),
    mkSeg({type:'play',game:'vault',title:'آماده‌سازی فینال',subtitle:'داور نزدیک‌تر میاد',v7:'VAULT_ARMED',notes:'نفر دوم ایزوله ۱۵+ متر · رمز کیف قبل از REC مهر شود',duration:20,reward:0,status:'ok',lines:[L('suspense','داور نزدیک‌تر میاد.')]}),
    mkSeg({type:'rules',game:'vault',title:'قانون گاوصندوق',v7:'VAULT_ARMED',rules:['ساعت هر نفر = بانکش · اول نفر عقب، بعد جلو','ایستگاه ۱: نقاشی کور ← کد C1','ایستگاه ۲: اتاق حافظه، ۸ لیوان · اشتباه ۳− ← کد C2','ایستگاه ۳: معمای خنده‌دار · غلط = ۵ ثانیه قفل ← کد C3','کدها = رمز واقعی کیف · رمز غلط = ۵ ثانیه قفل','بیشترین زمان باقی‌مانده برندهٔ کیف است'],status:'ok',lines:[L('calm','ساعت هر نفر، همون بانکشه. اول نفر عقب.'),L('calm','ایستگاه یک: نقاشی کور.'),L('serious','ایستگاه دو: اتاق حافظه. هشت لیوان.'),L('playful','ایستگاه سه: یه معمای خنده‌دار.'),L('suspense','سه کد، همون رمز واقعی کیفه.'),L('epic','هر کی با زمان بیشتر باز کنه، کیف مال اونه.')]}),
    mkSeg({type:'play',game:'vault',title:'فینال · دویدن اول',subtitle:'نفر عقب',v7:'RUN1',duration:120,reward:0,status:'ok',lines:[L('playful','حافظه‌ت رفته مرخصی.'),L('celebrate','مغزت روشن شد.')]}),
    mkSeg({type:'play',game:'vault',title:'فینال · دویدن دوم',subtitle:'نفر جلو',v7:'RUN2',duration:120,reward:0,status:'ok',lines:[L('referee','نه. پنج ثانیه فکر کن.')]}),
    mkSeg({type:'play',game:'case',title:'کیف طلایی',subtitle:'رمز واقعی · رقم به رقم',v7:'CASE',duration:20,reward:0,status:'ok',lines:[L('suspense','برنده‌ی کیف…')]}),
    mkSeg({type:'play',game:'case',title:'لایهٔ ۱ · تاج داداش',subtitle:'نشان ساندویچ طلایی',v7:'CASE_L1',duration:20,reward:0,status:'ok',lines:[L('celebrate','نشان ساندویچ طلایی. اوّلین نشان روی تاج.')]}),
    mkSeg({type:'play',game:'case',title:'لایهٔ ۲ · پاکت سرنوشت',subtitle:'۱۲ پاکت · هیچ‌کس ندیده',v7:'CASE_L2',duration:20,reward:0,status:'ok',lines:[L('whisper','پاکت‌ها رو هیچ‌کس ندیده. حتی من. و من همه چی رو می‌بینم.')]}),
    mkSeg({type:'play',game:'case',title:'لایهٔ ۳ · پاکت مجازات',subtitle:'بازنده ۲ جعبه از ۶',v7:'CASE_L3',duration:20,reward:0,status:'ok',lines:[L('playful','چون من داورم. و داور عاشق عدالته.')]}),
    mkSeg({type:'winner',title:'دفاع از تاج',subtitle:'قسمت بعد · مجازات با رأی کامنت‌ها',v7:'END',status:'ok',lines:[L('epic','قسمت بعد… دفاع از تاج.')]})
  ]}}
